# spring 环境配置
spring:
  redis:
    host: 10.4.208.132
    port: 6379
    password: ZmkDbgaua3Rso33T
    database: 0

sei:
  cache:
    # 是否使用本地缓存, 默认开启
    enable-local: true
    # 是否使用redis缓存, 默认开启
    enable-redis: true
    # 默认过期时间(毫秒), 默认10分钟
    expire: 600000
  http:
    filter:
      enable: false

